### ISSUE TITLE
Ceiling division support in Cryptol client

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/argo#107]
```test.py
import argo.connection as argo
import cryptol

c = cryptol.connect(
      argo.ServerConnection(
        argo.RemoteSocketProcess('localhost', 36661, ipv6=True)))

c.load_module("test")
cryptol.add_cryptol_module('CryptolTest', c)
from CryptolTest import *
```

```test.cry
module test where

f : {n} (fin n) => [n] -> [n /^ 1]
f a = a
```

```shell
$ python3.7 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    cryptol.add_cryptol_module('CryptolTest', c)
  File "python/cryptol/__init__.py", line 366, in add_cryptol_module
    sys.modules[name] = CryptolModule(connection)
  File "python/cryptol/__init__.py", line 358, in __init__
    cryptoltypes.to_schema(x['type'])))
  File "python/cryptol/cryptoltypes.py", line 350, in to_schema
    to_type(obj['type']))
  File "python/cryptol/cryptoltypes.py", line 304, in to_type
    return Function(to_type(t['domain']), to_type(t['range']))
  File "python/cryptol/cryptoltypes.py", line 306, in to_type
    return Bitvector(to_type(t['width']))
  File "python/cryptol/cryptoltypes.py", line 332, in to_type
    raise NotImplementedError(f"to_type({t!r})")
NotImplementedError: to_type({'arguments': [{'kind': 'Num', 'name': 'n', 'type': 'variable'}, {'value': 1, 'type': 'number'}], 'type': '/^'})
```

**Comment by pnwamk** [comment]
See https://github.com/GaloisInc/argo/pull/112 and https://github.com/GaloisInc/cryptol/pull/945
